openapi: 3.1.0
info:
  title: Task Manager API
  version: 1.0.0
  description: API documentation for the Task Manager app
servers:
  - url: http://localhost:5050
    description: Local server

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Missing or invalid fields / User already exists

  /api/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

  /api/auth/logout:
    post:
      summary: Logout user
      responses:
        '200':
          description: Logout successful

  /api/auth/me:
    get:
      summary: Get current authenticated user
      responses:
        '200':
          description: Returns the current user
        '401':
          description: Not authenticated

  /api/auth/admin-only:
    get:
      summary: Admin-only route
      responses:
        '200':
          description: Admin dashboard data
        '403':
          description: Forbidden

  /api/auth/forgot-password:
    post:
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset email sent
        '404':
          description: User not found

  /api/auth/reset-password:
    post:
      summary: Reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password reset successful
        '400':
          description: Invalid token or new password missing